#!/bin/bash
"Alea iacta est ("The die is cast") is a variation of a Latin phrase (iacta alea est [ˈjakta ˈaːlɛ.a ˈɛs̺t]) attributed by Suetonius to Julius Caesar on 10 January 49 BC, as he led his army across the Rubicon river in Northern Italy, between Cesena and Rimini, in defiance of the Roman Senate and beginning a long civil war against Pompey and the Optimates. The phrase is often used to indicate events that have passed a point of no return.

According to Plutarch, Caesar originally said the line in Greek rather than Latin, as ἀνερρίφθω κύβος anerrhī́phthō kýbos, literally "let a die be cast", metaphorically "let the game be played". This is a quote from a play by Menander, and Suetonius's Latin translation is slightly misleading, being merely a statement about the inevitability of what is to come, while the Greek original contains a self-encouragement to venture forward. The Latin version is now most commonly cited with the word order changed (Alea iacta est), and it is used both in this form, and in translation in many languages. The same event inspired another related idiom, "crossing the Rubicon".
Caesar probably borrowed the phrase from Menander, the famous Greek writer of comedies, as the phrase appeared in Menander's lost play Arrephoros ('The Bearer of Ritual Objects'),[note 1] and Caesar was known to have considered him a great playwright.[note 2] Plutarch reports that Caesar quoted these words in Greek:

Ἑλληνιστὶ πρὸς τοὺς παρόντας ἐκβοήσας, «Ἀνερρίφθω κύβος», [anerrhī́phthō kýbos] διεβίβαζε τὸν στρατόν.[3]

He [Caesar] declared in Greek with loud voice to those who were present "Let a die be cast" and led the army across.

— Plutarch, Life of Pompey, 60.2.9[4]
Appian, also writing in Greek, reports a very similar phrase, and states that it was familiar (a well-known saying or quote):

καὶ εἰπὼν οἷά τις ἔνθους ἐπέρα σὺν ὁρμῇ, τὸ κοινὸν τόδε ἐπειπών· «Ὁ κύβος ἀνερρίφθω».

Then speaking like a man inspired, he surged across, uttering the familiar phrase, "Let the die be cast".

— Appian, The Civil Wars, 2.35[5]
Suetonius, a contemporary of Plutarch and Appian, writing in Latin, has the quote in Latin instead of Greek:
Suetonius, a contemporary of Plutarch and Appian, writing in Latin, has the quote in Latin instead of Greek:
